### ISSUE TITLE
Need ability to create machine without any public ports

### ISSUE THREAD

**Issue by kdevan** [fly-apps/terraform-provider-fly#137]
Most of my apps do not expose any public ports and are accessed through caddy as a proxy. It looks like I can't create a machine that doesn't expose any public ports though.

The `ports` key and then the `port` key are both required. Is there a way to bypass this by any chance? I do need the `internal_port` and have that set along with `protocol`.

I'm hoping to be able to do something like this:

```
services = [
    {
      internal_port =  9100
      protocol = "tcp"
    },
    {
      internal_port = 9101
      protocol = "tcp"
    }
]
```

![Screenshot from 2023-01-12 22-14-14](https://user-images.githubusercontent.com/1412685/212251657-efdea428-354a-4d54-86de-0de4b3e57f58.png)

**Comment by OJFord** [comment]
My understanding is that if you don't specify any `services` it's still exposed on the private network (any port) - this is just for exposing public ports. Is that not working?

https://fly.io/docs/reference/configuration/#the-services-sections

> You can have:
> * No services section: The application has no mappings to the external internet - typically apps like databases that talk over 6PN private networking to other apps.
>
> [...]

(Yes these docs are about `fly.toml`, but that `[services]` section is the equivalent of here. Note also that the [private networking docs](https://fly.io/docs/reference/private-networking/) make no mention of this stuff, while the [public networking docs](https://fly.io/docs/reference/services/) do, and while titled 'public networking', the URL is even `.../services`.)

**Comment by OJFord** [comment]
Ah I did have to fiddle with a bit myself in the end - you do need the services, just don't attach a `fly_ip` to the app and it will only be available on the private network.

The `ports` key _is_ still required, because that's still your mapping from port number outside vs inside the VM. Just like if you ran it with e.g. docker locally to test, you'd have `-p 1234:80` say (or `80:80`) or equivalent in compose. 

The `internal_port` is the the port that's bound to in whatever you're running, `EXPOSE`d in the dockerfile, and the `ports` are those that should map into it on the machine itself - i.e. completely arbitrary, just has to match whatever you put in `reverse_proxy` in Caddy.

**Comment by kdevan** [comment]
Ok interesting. Thanks for the information. I believe I'll have a chance to try this out this weekend, I'll give an update here when I do.

**Comment by kdevan** [comment]
Working great. That clarifies a lot for me, even just with machines in general. Was mostly using v1 apps before this. Thanks!
